### ISSUE TITLE
Can you decouple the glow?

### ISSUE THREAD

**Issue by e200** [ChristianIvicevic/ModernChrome#1]
Please, see: https://github.com/MahApps/MahApps.Metro/issues/3051.

Please!

**Comment by ChristianIvicevic** [comment]
Currently I am not considering to decouple the behavior since it relies heavily on internals of *MahApps.Metro* itself and I'd rather just reference the package.

If you are interested in helping out you'd need to do the following steps:

- Create a custom `Window` class that contains two dependency properties `GlowBrush` ([here](https://github.com/ChristianIvicevic/ModernChrome/blob/6f75a2ed99d3cd44c30ef354e1b9e4e992d019b4/ModernChrome/ModernWindow.cs#L26)) and `NonActiveGlowBrush` ([here](https://github.com/ChristianIvicevic/ModernChrome/blob/6f75a2ed99d3cd44c30ef354e1b9e4e992d019b4/ModernChrome/ModernWindow.cs#L32)).
- Introduce a class `GlowWindowBehavior` [like this](https://github.com/ChristianIvicevic/ModernChrome/blob/master/ModernChrome/Behaviors/GlowWindowBehavior.cs) which references your custom `Window` class.
- The `GlowWindowBehavior` depends on multiple parts from the _MahApps.Metro_ package:
    - [`Glow.cs`](https://github.com/MahApps/MahApps.Metro/blob/336f7dfc4bda2d0eba8aa270737ca3c11d45128c/src/MahApps.Metro/MahApps.Metro.Shared/Controls/Glow.cs)
    - [`GlowDirection.cs`](https://github.com/MahApps/MahApps.Metro/blob/336f7dfc4bda2d0eba8aa270737ca3c11d45128c/src/MahApps.Metro/MahApps.Metro.Shared/Controls/GlowDirection.cs)
    - [`GlowWindow.xaml`](https://github.com/MahApps/MahApps.Metro/blob/336f7dfc4bda2d0eba8aa270737ca3c11d45128c/src/MahApps.Metro/MahApps.Metro.Shared/Controls/GlowWindow.xaml)
    - [`GlowWindow.xaml.cs`](https://github.com/MahApps/MahApps.Metro/blob/336f7dfc4bda2d0eba8aa270737ca3c11d45128c/src/MahApps.Metro/MahApps.Metro.Shared/Controls/GlowWindow.xaml.cs)
- The `GlowWindow.xaml.cs` class uses native methods via P/Invoke which are stored in `NativeMethods` that one would need to decouple as well.

In the end I assume it is just easier to derive from `MetroWindow`, apply the glow and just not care. You might as well fork my project and remove the `ModernWindowChrome` as well as the template in `Generic.xaml` to reduce the clutter.

**Comment by codehulk75** [comment]
Why would you want to? It's an elegant feature. In fact, I was looking to do this whole thing myself until I found this repo. It's perfect and has saved me a lot of time so I can just get on to the logic that much quicker. Thanks!
